<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>LensSplitter.Visualization</RootNamespace>
    <AssemblyName>LensSplitter.Visualization</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LensSplitter.Core\LensSplitter.Core.csproj" />
  </ItemGroup>
</Project>
