using System.Globalization;
using System.Text;
using LensSplitter.Core.Models;

namespace LensSplitter.Parsing.Export;

/// <summary>
/// Exports optical systems to ZEMAX ZMX format.
/// </summary>
public class ZmxExporter
{
    /// <summary>
    /// Exports an optical system to a ZMX file.
    /// </summary>
    /// <param name="system">The optical system to export.</param>
    /// <param name="path">Output file path.</param>
    public void Export(OpticalSystem system, string path)
    {
        var content = GenerateZmx(system);
        File.WriteAllText(path, content, Encoding.Unicode); // UTF-16 LE
    }

    /// <summary>
    /// Generates ZMX file content.
    /// </summary>
    /// <param name="system">The optical system.</param>
    /// <returns>ZMX file content.</returns>
    public string GenerateZmx(OpticalSystem system)
    {
        var sb = new StringBuilder();

        // Header
        sb.AppendLine($"! {system.Name}");
        sb.AppendLine($"! Generated by LensSplitter");
        sb.AppendLine($"! {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine();

        // Mode and units
        sb.AppendLine("MODE SEQ");
        sb.AppendLine("UNIT MM X W X CM MR CPMM");
        sb.AppendLine();

        // Aperture
        WriteAperture(sb, system);
        sb.AppendLine();

        // Wavelengths
        WriteWavelengths(sb, system);
        sb.AppendLine();

        // Fields
        WriteFields(sb, system);
        sb.AppendLine();

        // Surfaces
        WriteSurfaces(sb, system);

        return sb.ToString();
    }

    private void WriteAperture(StringBuilder sb, OpticalSystem system)
    {
        switch (system.ApertureType)
        {
            case ApertureType.EntrancePupilDiameter:
                sb.AppendLine($"ENPD {FormatDouble(system.ApertureValue)}");
                break;
            case ApertureType.ImageSpaceFNumber:
                sb.AppendLine($"FLOA");
                sb.AppendLine($"FNUM {FormatDouble(system.ApertureValue)}");
                break;
            default:
                sb.AppendLine($"ENPD {FormatDouble(system.ApertureValue)}");
                break;
        }
    }

    private void WriteWavelengths(StringBuilder sb, OpticalSystem system)
    {
        // Find primary wavelength index
        int primaryIdx = system.Wavelengths.FindIndex(w => w.IsPrimary);
        if (primaryIdx < 0) primaryIdx = 0;

        sb.AppendLine($"PWAV {primaryIdx + 1}");

        for (int i = 0; i < system.Wavelengths.Count; i++)
        {
            var wave = system.Wavelengths[i];
            sb.AppendLine($"WAVM {i + 1} {FormatDouble(wave.ValueMicrons)} {FormatDouble(wave.Weight)}");
        }
    }

    private void WriteFields(StringBuilder sb, OpticalSystem system)
    {
        if (system.Fields.Count == 0) return;

        // Field type - ZEMAX codes: 0=Angle, 1=ObjectHeight, 2=ParaxialImageHeight, 3=RealImageHeight
        var fieldType = system.Fields[0].FieldType;
        int ftyp = fieldType switch
        {
            FieldType.Angle => 0,
            FieldType.ObjectHeight => 1,
            FieldType.ParaxialImageHeight => 2,
            FieldType.ImageHeight => 3,  // Real image height
            _ => 0
        };

        sb.AppendLine($"FTYP {ftyp} 0 {system.Fields.Count} {system.Wavelengths.Count} 0 0 0");

        // X field values
        sb.Append("XFLN");
        foreach (var field in system.Fields)
        {
            sb.Append($" {FormatDouble(field.X)}");
        }
        sb.AppendLine();

        // Y field values
        sb.Append("YFLN");
        foreach (var field in system.Fields)
        {
            sb.Append($" {FormatDouble(field.Y)}");
        }
        sb.AppendLine();

        // Field weights
        sb.Append("FWGN");
        foreach (var field in system.Fields)
        {
            sb.Append($" {FormatDouble(field.Weight)}");
        }
        sb.AppendLine();
    }

    private void WriteSurfaces(StringBuilder sb, OpticalSystem system)
    {
        foreach (var surface in system.Surfaces)
        {
            WriteSurface(sb, surface);
        }
    }

    private void WriteSurface(StringBuilder sb, Surface surface)
    {
        sb.AppendLine($"SURF {surface.Index}");

        // Stop
        if (surface.IsStop)
        {
            sb.AppendLine($"STOP");
        }

        // Type
        string surfType = surface.SurfaceType switch
        {
            SurfaceType.Standard => "STANDARD",
            SurfaceType.EvenAsphere => "EVENASPH",
            SurfaceType.Paraxial => "PARAXIAL",
            SurfaceType.CoordinateBreak => "COORDBRK",
            _ => "STANDARD"
        };
        sb.AppendLine($"TYPE {surfType}");

        // Curvature
        double curv = surface.IsFlat ? 0.0 : 1.0 / surface.Radius;
        sb.AppendLine($"CURV {FormatDouble(curv)}");

        // Thickness
        if (double.IsInfinity(surface.Thickness))
        {
            sb.AppendLine($"DISZ INFINITY");
        }
        else
        {
            sb.AppendLine($"DISZ {FormatDouble(surface.Thickness)}");
        }

        // Marginal ray height solve (MAZH)
        if (surface.HasMarginalRayHeightSolve)
        {
            sb.AppendLine($"MAZH {surface.MarginalRayHeightSolveParams ?? "0 0"}");
        }

        // Glass
        if (surface.Glass != null && surface.Glass.Name != "AIR" && !string.IsNullOrEmpty(surface.Glass.Name))
        {
            sb.AppendLine($"GLAS {surface.Glass.Name}");
        }
        else if (!string.IsNullOrEmpty(surface.GlassName) && surface.GlassName != "AIR")
        {
            sb.AppendLine($"GLAS {surface.GlassName}");
        }

        // Semi-diameter
        if (surface.SemiDiameter > 0)
        {
            sb.AppendLine($"DIAM {FormatDouble(surface.SemiDiameter)}");
        }

        // Conic
        if (Math.Abs(surface.Conic) > 1e-10)
        {
            sb.AppendLine($"CONI {FormatDouble(surface.Conic)}");
        }

        // Comment
        if (!string.IsNullOrEmpty(surface.Comment))
        {
            sb.AppendLine($"COMM {surface.Comment}");
        }
    }

    private static string FormatDouble(double value)
    {
        if (double.IsInfinity(value)) return "Infinity";
        if (double.IsNaN(value)) return "0";

        // Use scientific notation for very small or large numbers
        if (Math.Abs(value) < 1e-10) return "0";
        if (Math.Abs(value) < 0.001 || Math.Abs(value) > 1e6)
        {
            return value.ToString("E10", CultureInfo.InvariantCulture);
        }

        return value.ToString("G10", CultureInfo.InvariantCulture);
    }
}
